"""Inverse warping utilities for geometric turbulence correction."""

from __future__ import annotations

import cv2
import numpy as np


def revert_deformation(target_img: np.ndarray, flow: np.ndarray) -> np.ndarray:
    """Apply backward warping to restore geometry using a dense flow field.

    Args:
        target_img: Distorted image to be corrected.
        flow: Flow field of shape ``(H, W, 2)`` mapping reference-to-target
            displacements.

    Returns:
        Corrected image generated by Lanczos interpolation and border replication.
    """
    h, w = target_img.shape[:2]
    x_coords, y_coords = np.meshgrid(np.arange(w), np.arange(h))

    map_x = (x_coords.astype(np.float32) + flow[:, :, 0]).astype(np.float32)
    map_y = (y_coords.astype(np.float32) + flow[:, :, 1]).astype(np.float32)

    return cv2.remap(
        target_img,
        map_x,
        map_y,
        interpolation=cv2.INTER_LANCZOS4,
        borderMode=cv2.BORDER_REPLICATE,
    )
